root: true
parser: "@typescript-eslint/parser"
env:
  es6: true
  node: true
  commonjs: true
  mocha: true
extends:
  - "eslint-config-airbnb-base"
plugins:
  - "@typescript-eslint/eslint-plugin"
  - "import"
parserOptions:
  project: "./tsconfig.json"
settings:
  import/resolver:
    node:
      extensions: [".ts", ".tsx", ".js", ".jsx", ".json"]
rules:
  comma-dangle:
    - 2
    - only-multiline
  indent:
    - error
    - 4
  no-confusing-arrow: 0
  react/jsx-no-bind: 0
  react-hooks/exhaustive-deps: 0
  import/extensions: 0
  consistent-return: 0
  brace-style:
    - error
    - stroustrup
  object-curly-spacing:
    - error
    - never
  import/no-extraneous-dependencies: 0
