root: true
parser: "@typescript-eslint/parser"
env:
  es6: true
  node: true
  commonjs: true
  mocha: true
extends:
  - "eslint-config-airbnb-base"
plugins:
  - "@typescript-eslint/eslint-plugin"
  - "import"
parserOptions:
  project: "./tsconfig.json"
settings:
  import/resolver:
    node:
      extensions: [".ts", ".tsx", ".js", ".jsx", ".json"]
rules:
  comma-dangle:
    - error
    - always-multiline
  indent:
    - error
    - 4
  max-len:
    - error
    - code: 120
  brace-style:
    - error
    - stroustrup
  object-curly-spacing:
    - error
    - never
  import/order:
    - error
    - groups:
      - ['builtin', 'external']
      - ['internal', 'sibling', 'parent', 'index']
      - 'unknown'
      newlines-between: always
  no-confusing-arrow: 0
  react/jsx-no-bind: 0
  react-hooks/exhaustive-deps: 0
  import/extensions: 0
  consistent-return: 0
  arrow-parens: 0
  no-shadow: 0
  no-console: 0
  no-mixed-operators: 0
  object-curly-newline: 0
  lines-between-class-members: 0
  import/prefer-default-export: 0
  import/no-extraneous-dependencies: 0
